apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepsparse-deployment
  labels:
    app: deepsparse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepsparse
  template:
    metadata:
      labels:
        app: deepsparse
    spec:
      containers:
      - name: deepsparse
        image: deepsparse
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 2
            memory: "4Gi"
          limits:
            cpu: 2
            memory: "4Gi"
        ports:
        - containerPort: 5543
---
